version: 0.2
phases:
  install:
    commands:
      - sudo npm install
   build:
    commands:
      - "sudo npm run-scripts build"   
artifacts:
  files:
    - '**/*' #copy all build files to S3 location
